image: node:20-alpine

variables:
  JWT_SECRET: "ci-test-secret-minimum-32-characters-ok"

ci:
  script:
    - npm install --no-save
        jest ts-jest jest-environment-node @types/jest
        typescript ts-node
        jsonwebtoken @types/jsonwebtoken
        bcryptjs @types/bcryptjs
        mongodb
    - npm test
  only:
    - main
    - merge_requests
